#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER_AGENT="Minecera/1.0 (https://github.com/Censera/minecera)"
LISTS=(
    "$ROOT/datapacks.list"
    "$ROOT/plugins.list"
    "$ROOT/resources.list"
    "$ROOT/mcpacks.list"
    "$ROOT/paper.list"
)

LIST_DESTINATION=""
LIST_NAMES=()
LIST_URLS=()

report() {
    printf '[%s] %s\n' "$(date '+%F %T')" "$*"
}

parse_list() {
    local list="$1"
    local line line_number=0
    local destination_set=0

    LIST_DESTINATION=""
    LIST_NAMES=()
    LIST_URLS=()

    [[ -f "$list" ]] || {
        echo "missing list: $list" >&2
        return 1
    }

    while IFS= read -r line || [ -n "$line" ]; do
        line_number=$((line_number + 1))
        line="${line%$'\r'}"
        line="${line%%#*}"
        line="${line##+([[:space:]])}"
        line="${line%%+([[:space:]])}"

        [[ -n "$line" ]] || continue

        if [ "$destination_set" -eq 0 ]; then
            if [[ "$line" =~ ^destination[[:space:]]+"([^"]+)"$ ]]; then
                LIST_DESTINATION="${BASH_REMATCH[1]}"
                destination_set=1
            else
                echo "$list:$line_number: expected: destination \"to/path\"" >&2
                return 1
            fi
            continue
        fi

        if [[ ! "$line" =~ ^([^[:space:]()]+)[[:space:]]+\((https?://[^)]+)\)$ ]]; then
            echo "$list:$line_number: expected: file.extension (direct-download-link)" >&2
            return 1
        fi

        LIST_NAMES+=("${BASH_REMATCH[1]}")
        LIST_URLS+=("${BASH_REMATCH[2]}")
    done < "$list"

    [ "$destination_set" -eq 1 ] || {
        echo "$list: missing destination declaration" >&2
        return 1
    }

    case "$LIST_DESTINATION" in
        /*|..|../*|*/../*|*/..)
            echo "$list: destination must stay inside Minecera" >&2
            return 1
            ;;
    esac

    mkdir -p "$ROOT/$LIST_DESTINATION"
}

clean_list() {
    local destination="$ROOT/$LIST_DESTINATION"
    local name extension file
    declare -A wanted=()
    declare -A extensions=()

    for name in "${LIST_NAMES[@]}"; do
        wanted["$name"]=1
        extension="${name##*.}"
        extensions["$extension"]=1
    done

    for extension in "${!extensions[@]}"; do
        while IFS= read -r -d '' file; do
            name="$(basename -- "$file")"
            if [[ -z "${wanted[$name]+x}" ]]; then
                rm -f -- "$file"
                report "removed stale $LIST_DESTINATION/$name"
            fi
        done < <(find "$destination" -maxdepth 1 -type f -name "*.$extension" -print0)
    done
}

download_list() {
    local list="$1"
    local destination="$ROOT/$LIST_DESTINATION"
    local index name url temp

    for index in "${!LIST_NAMES[@]}"; do
        name="${LIST_NAMES[$index]}"
        url="${LIST_URLS[$index]}"
        temp="$destination/.${name}.part"

        printf '  %-40s' "$name"
        rm -f -- "$temp"

        if curl --fail --silent --show-error --location \
            --retry 5 --retry-delay 1 --retry-all-errors \
            --connect-timeout 15 --max-time 300 \
            --user-agent "$USER_AGENT" \
            --output "$temp" -- "$url"; then
            if [[ ! -s "$temp" ]]; then
                rm -f -- "$temp"
                echo "FAILED (empty response)" >&2
                return 1
            fi
            mv -f -- "$temp" "$destination/$name"
            echo "ok"
        else
            rm -f -- "$temp"
            echo "FAILED" >&2
            echo "    $url" >&2
            return 1
        fi
    done
}

generate_forcepack_config() {
    local destination="$LIST_DESTINATION"
    local config="$ROOT/plugins/ForcePack/config.yml"
    local temp="$ROOT/plugins/ForcePack/.config.yml.part"
    local index name url clean_url hash

    [ "$destination" = "resourcepacks" ] || return 0
    [ -f "$ROOT/plugins/ForcePack.jar" ] || return 0

    mkdir -p "$ROOT/plugins/ForcePack"

    {
        cat <<'EOF'
# Generated by Minecera setup.sh.
# Source of truth: resources.list
velocity-mode: false
prevent-movement: false
prevent-damage: false
enable-mc-164316-fix: true
load-last: false
await-items-adder-host: true
use-new-force-pack-screen: true
try-to-stop-fake-accept-hacks: false
send-loading-title: false
delay-pack-sending-by: 0
web-server:
  enabled: false
  protocol: "http://"
  server-ip: localhost
  port: 8080
  port-on-url: true
Server:
  packs:
    all:
      urls:
EOF

        for index in "${!LIST_NAMES[@]}"; do
            name="${LIST_NAMES[$index]}"
            url="${LIST_URLS[$index]}"
            clean_url="${url%%\?*}"

            [ -f "$ROOT/$destination/$name" ] || {
                echo "missing downloaded resource pack: $ROOT/$destination/$name" >&2
                return 1
            }

            printf '        - "%s"\n' "$clean_url"
        done

        cat <<'EOF'
      generate-hash: false
      hashes:
EOF

        for index in "${!LIST_NAMES[@]}"; do
            name="${LIST_NAMES[$index]}"
            hash="$(sha1sum -- "$ROOT/$destination/$name" | cut -d ' ' -f1 | tr '[:lower:]' '[:upper:]')"
            printf '        - "%s"\n' "$hash"
        done

        cat <<'EOF'
  Actions:
    ACCEPTED:
      kick: false
      Commands: []
    DOWNLOADED:
      kick: false
      Commands: []
    SUCCESSFULLY_LOADED:
      kick: false
      Commands: []
    DECLINED:
      kick: false
      Commands: []
    FAILED_DOWNLOAD:
      kick: false
      Commands: []
    FAILED_RELOAD:
      kick: false
      Commands: []
    DISCARDED:
      kick: false
      Commands: []
  Update GUI Speed: 20
  Update GUI: true
  verify: true
  resend: true
  force-invalid-size: false
  geyser: true
  bypass-permission: false
  debug: false
EOF
    } > "$temp"

    mv -f -- "$temp" "$config"
    report "ForcePack config generated"
}

for list in "${LISTS[@]}"; do
    report "processing $(basename "$list")"
    parse_list "$list"
    clean_list
    download_list "$list"
    if [ "$(basename "$list")" = "resources.list" ]; then
        generate_forcepack_config
    fi
    echo
done

report "Setup complete."
