#!/usr/bin/env bash
set -euo pipefail

PLUGINS_DIR="plugins"
DATAPACKS_DIR="world/datapacks"
RESOURCEPACKS_DIR="resourcepacks"
FORCEPACK_DIR="$PLUGINS_DIR/ForcePack"

mkdir -p "$PLUGINS_DIR" "$DATAPACKS_DIR" "$RESOURCEPACKS_DIR"

clean_managed_files() {
    local list="$1"
    local destination="$2"
    local extension="$3"
    local line name url pattern file
    declare -A wanted=()

    [[ -f "$list" ]] || return 0
    pattern='^(.+)[[:space:]]\((https?://[^)]*)\)$'

    while IFS= read -r line || [ -n "$line" ]; do
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        [[ "$line" =~ $pattern ]] || {
            echo "invalid entry in $list: $line" >&2
            return 1
        }
        name="${BASH_REMATCH[1]}"
        wanted["$name"]=1
    done < "$list"

    while IFS= read -r -d '' file; do
        name="$(basename -- "$file")"
        [[ -n "${wanted[$name]+x}" ]] || rm -f -- "$file"
    done < <(find "$destination" -maxdepth 1 -type f -name "*.$extension" -print0)
}

download_list() {
    local list="$1"
    local destination="$2"
    local line name url tmp pattern

    [[ -f "$list" ]] || return 0
    pattern='^(.+)[[:space:]]\((https?://[^)]*)\)$'

    while IFS= read -r line || [ -n "$line" ]; do
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

        if [[ ! "$line" =~ $pattern ]]; then
            echo "invalid entry in $list: $line" >&2
            return 1
        fi

        name="${BASH_REMATCH[1]}"
        url="${BASH_REMATCH[2]}"
        tmp="$destination/.${name}.part"

        printf '  %-40s' "$name"
        rm -f -- "$tmp"

        if curl --fail --silent --show-error --location \
            --retry 5 --retry-delay 1 --retry-all-errors \
            --connect-timeout 15 --max-time 300 \
            --output "$tmp" -- "$url"; then
            if [[ ! -s "$tmp" ]]; then
                rm -f -- "$tmp"
                echo "FAILED (empty response)" >&2
                return 1
            fi
            mv -f -- "$tmp" "$destination/$name"
            echo "ok"
        else
            rm -f -- "$tmp"
            echo "FAILED" >&2
            echo "    $url" >&2
            return 1
        fi
    done < "$list"
}

generate_forcepack_config() {
    local list="$RESOURCEPACKS_DIR/resourcepacks.list"
    local config tmp line name url clean_url hash pattern

    [[ -f "$list" ]] || return 0
    [[ -f "$PLUGINS_DIR/ForcePack.jar" ]] || return 0

    mkdir -p "$FORCEPACK_DIR"
    config="$FORCEPACK_DIR/config.yml"
    tmp="$FORCEPACK_DIR/.config.yml.part"
    pattern='^(.+)[[:space:]]\((https?://[^)]*)\)$'

    {
        cat <<'EOF'
# Generated by Minecera setup.sh.
# Source of truth: resourcepacks/resourcepacks.list
velocity-mode: false
prevent-movement: false
prevent-damage: false
enable-mc-164316-fix: true
load-last: false
await-items-adder-host: true
use-new-force-pack-screen: false
try-to-stop-fake-accept-hacks: false
send-loading-title: false
delay-pack-sending-by: 0
web-server:
  enabled: false
  protocol: "http://"
  server-ip: localhost
  port: 8080
  port-on-url: true
Server:
  packs:
    all:
      urls:
EOF

        while IFS= read -r line || [ -n "$line" ]; do
            [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
            [[ "$line" =~ $pattern ]] || {
                echo "invalid entry in $list: $line" >&2
                return 1
            }

            name="${BASH_REMATCH[1]}"
            url="${BASH_REMATCH[2]}"
            clean_url="${url%%\?*}"

            [[ -f "$RESOURCEPACKS_DIR/$name" ]] || {
                echo "missing downloaded resource pack: $RESOURCEPACKS_DIR/$name" >&2
                return 1
            }

            printf '        - "%s"\n' "$clean_url"
        done < "$list"

        cat <<'EOF'
      generate-hash: false
      hashes:
EOF

        while IFS= read -r line || [ -n "$line" ]; do
            [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
            [[ "$line" =~ $pattern ]] || return 1

            name="${BASH_REMATCH[1]}"
            hash="$(sha1sum -- "$RESOURCEPACKS_DIR/$name" | cut -d ' ' -f1 | tr '[:lower:]' '[:upper:]')"
            printf '        - "%s"\n' "$hash"
        done < "$list"

        cat <<'EOF'
  Actions:
    ACCEPTED:
      kick: false
      Commands: []
    DOWNLOADED:
      kick: false
      Commands: []
    SUCCESSFULLY_LOADED:
      kick: false
      Commands: []
    DECLINED:
      kick: false
      Commands: []
    FAILED_DOWNLOAD:
      kick: false
      Commands: []
    FAILED_RELOAD:
      kick: false
      Commands: []
    DISCARDED:
      kick: false
      Commands: []
  Update GUI Speed: 20
  Update GUI: true
  verify: true
  resend: true
  force-invalid-size: false
  geyser: true
  bypass-permission: false
  debug: false
EOF
    } > "$tmp"

    mv -f -- "$tmp" "$config"
    echo "ForcePack config generated with deterministic pack order."
}

echo "Cleaning plugins..."
clean_managed_files "$PLUGINS_DIR/plugin.list" "$PLUGINS_DIR" jar
echo "Downloading plugins..."
download_list "$PLUGINS_DIR/plugin.list" "$PLUGINS_DIR"
echo
echo "Cleaning datapacks..."
clean_managed_files "$DATAPACKS_DIR/datapacks.list" "$DATAPACKS_DIR" zip
echo "Downloading datapacks..."
download_list "$DATAPACKS_DIR/datapacks.list" "$DATAPACKS_DIR"
echo
echo "Cleaning resource packs..."
clean_managed_files "$RESOURCEPACKS_DIR/resourcepacks.list" "$RESOURCEPACKS_DIR" zip
echo "Downloading resource packs..."
download_list "$RESOURCEPACKS_DIR/resourcepacks.list" "$RESOURCEPACKS_DIR"
echo
generate_forcepack_config
echo
echo "Setup complete."
