(() => {
'use strict';
const ranges=[['day',1],['week',7],['month',30],['year',365],['all',Infinity]];
let currentRange='week',rawPoints=[],visibleData=[],hoveredIndex=-1;
function mount(){const panel=document.querySelector('.chart-panel');if(!panel)return;panel.className='chart-panel player-history-panel';panel.innerHTML=`<div class="player-history"><h3 class="player-history-title">Player History</h3><canvas id="historyChart" width="500" height="200" aria-label="Player history line chart"></canvas><div class="player-history-stats"><div><span>Peak</span> <strong id="peakPlayers">--</strong></div><div><span>Avg</span> <strong id="avgPlayers">--</strong></div></div><div class="player-history-controls"><div class="player-history-ranges">${ranges.map(([n])=>`<button type="button" class="player-history-range${n===currentRange?' active':''}" data-range="${n}">${n[0].toUpperCase()+n.slice(1)}</button>`).join('')}</div></div></div>`;style();panel.querySelectorAll('.player-history-range').forEach(b=>b.onclick=()=>{currentRange=b.dataset.range;panel.querySelectorAll('.player-history-range').forEach(x=>x.classList.toggle('active',x===b));update()});const c=document.getElementById('historyChart');c.onmousemove=e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,l=35,rr=10; if(!visibleData.length||x<l-5||x>c.width-rr+5)hoveredIndex=-1;else{const s=(c.width-l-rr)/(visibleData.length-1||1);hoveredIndex=Math.max(0,Math.min(visibleData.length-1,Math.round((x-l)/s)))}draw()};c.onmouseleave=()=>{hoveredIndex=-1;draw()};addEventListener('resize',draw);load()}
function style(){if(document.getElementById('player-history-style'))return;const s=document.createElement('style');s.id='player-history-style';s.textContent='.chart-panel.player-history-panel{padding:0;overflow:hidden;background:#1e1e1e;border:0;border-radius:12px}.player-history{width:100%;padding:2rem;color:#e0e0e0}.player-history-title{margin:0 0 1.5rem;font-weight:400;font-size:1.2rem;letter-spacing:-.01em;color:#f0f0f0}#historyChart{display:block;width:100%;height:auto;background:#1a1a1a;border-radius:8px;cursor:crosshair}.player-history-stats{display:flex;gap:1.5rem;margin:1rem 0;font-size:.85rem;color:#b0b0b0}.player-history-stats div{display:flex;align-items:baseline;gap:.5rem}.player-history-stats span{color:#888;font-size:.8rem}.player-history-stats strong{color:#f5f5f5;font-size:.9rem;font-weight:400}.player-history-controls{display:flex;align-items:center;margin-top:1rem}.player-history-ranges{display:flex;gap:.6rem;flex-wrap:wrap}.player-history-range{background:none;border:0;border-radius:8px;padding:.5rem 1rem;font-size:.85rem;cursor:pointer;color:#ccc;font-weight:400}.player-history-range.active{background:#3a7afe;color:white}.player-history-range:hover:not(.active){background:#2a2a2a}@media(max-width:600px){.player-history{padding:1.25rem}.player-history-ranges{gap:.25rem}.player-history-range{padding:.45rem .75rem}}';document.head.append(s)}
function startDay(t){const d=new Date(t*1e3);d.setHours(0,0,0,0);return d.getTime()/1e3}
function daily(p){const m=new Map();for(const x of p){const d=startDay(Number(x.time)),e=m.get(d)||{time:d,sum:0,n:0};e.sum+=Number(x.count)||0;e.n++;m.set(d,e)}return [...m.values()].sort((a,b)=>a.time-b.time).map(e=>({time:e.time,count:Math.round(e.sum/e.n)}))}
function data(){const a=daily(rawPoints),r=ranges.find(x=>x[0]===currentRange);return r[1]===Infinity?a:a.slice(-r[1])}
function update(){visibleData=data();const c=visibleData.map(x=>x.count),p=document.getElementById('peakPlayers'),a=document.getElementById('avgPlayers');p.textContent=c.length?Math.max(...c):'--';a.textContent=c.length?Math.round(c.reduce((s,x)=>s+x,0)/c.length):'--';hoveredIndex=-1;draw()}
function draw(){const c=document.getElementById('historyChart');if(!c)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!visibleData.length)return;const l=35,r=10,t=10,b=25,gw=w-l-r,gh=h-t-b,v=visibleData.map(p=>p.count);let min=Math.min(...v),max=Math.max(...v),pad=Math.max(1,(max-min)*.1);min-=pad;max+=pad;if(max===min)max=min+1;const step=gw/(visibleData.length-1||1),pt=i=>({x:l+i*step,y:t+gh-((visibleData[i].count-min)/(max-min))*gh}),pts=visibleData.map((_,i)=>pt(i));x.strokeStyle='#2a2a2a';x.lineWidth=.5;x.font='10px system-ui,sans-serif';x.fillStyle='#888';x.textAlign='right';x.textBaseline='middle';for(let i=0;i<=4;i++){const val=min+i/4*(max-min),y=t+gh-i/4*gh;x.beginPath();x.moveTo(l,y);x.lineTo(w-r,y);x.stroke();x.fillText(Math.round(val),l-5,y)}x.textAlign='center';x.textBaseline='alphabetic';const fmt=q=>{const d=new Date(q*1e3);return currentRange==='day'?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString([],{month:'short',day:'numeric'})},last=pts.length-1;x.fillText(fmt(visibleData[0].time),l,h-8);if(last>1){const m=Math.floor(last/2);x.fillText(fmt(visibleData[m].time),pts[m].x,h-8)}x.fillText(fmt(visibleData[last].time),pts[last].x,h-8);x.beginPath();pts.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.strokeStyle='#4a8cff';x.lineWidth=2;x.lineJoin='round';x.stroke();pts.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,i===hoveredIndex?5:3,0,Math.PI*2);x.fillStyle=i===hoveredIndex?'#7fadff':'#4a8cff';x.fill()});if(hoveredIndex>=0){const p=pts[hoveredIndex];x.beginPath();x.moveTo(p.x,t);x.lineTo(p.x,t+gh);x.strokeStyle='#555';x.lineWidth=.8;x.setLineDash([3,3]);x.stroke();x.setLineDash([]);const s=`${visibleData[hoveredIndex].count} players`;x.font='11px system-ui,sans-serif';const bw=x.measureText(s).width+10,bx=Math.min(p.x+10,w-bw-5),by=Math.max(p.y-25,5);x.fillStyle='#2a2a2a';x.fillRect(bx,by,bw,20);x.fillStyle='#f0f0f0';x.textAlign='left';x.textBaseline='middle';x.fillText(s,bx+5,by+10)}}
async function load(){try{const r=await fetch('/api/player-count?points=2000',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();rawPoints=Array.isArray(d.points)?d.points:[]}catch{rawPoints=[]}update()}
addEventListener('DOMContentLoaded',mount)
})();
